// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import {
  Link,
  Text,
  RichText,
  NextImage,
  Placeholder as Placeholder_8a80e63291fea86e0744df19113dc44bec187216,
  AppPlaceholder,
  CdpHelper,
} from '@sitecore-content-sdk/nextjs';
import { Suspense } from 'react';
import React from 'react';
import { componentMap } from '.sitecore/component-map';
import client from 'src/lib/sitecore-client';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';

const importMapServer = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'Placeholder', value: Placeholder_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'AppPlaceholder', value: AppPlaceholder },
      { name: 'CdpHelper', value: CdpHelper },
    ],
  },
  {
    module: 'react',
    exports: [
      { name: 'Suspense', value: Suspense },
      { name: 'default', value: React },
    ],
  },
  {
    module: '.sitecore/component-map',
    exports: [{ name: 'componentMap', value: componentMap }],
  },
  {
    module: 'src/lib/sitecore-client',
    exports: [{ name: 'default', value: client }],
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [{ name: 'pageView', value: pageView }],
  },
  {
    module: 'sitecore.config',
    exports: [{ name: 'default', value: config }],
  },
];

export default combineImportEntries(defaultImportEntries, importMapServer);
