// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import { combineImportEntries, defaultImportEntries } from '@sitecore-content-sdk/nextjs/tools';
// end of built-in imports
    
const importMap = [];

export default combineImportEntries(defaultImportEntries, importMap);
